// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: trust.proto

package trustpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrustEngine_RunVeriRank_FullMethodName       = "/verilink.trust.v1.TrustEngine/RunVeriRank"
	TrustEngine_VerifyAttestation_FullMethodName = "/verilink.trust.v1.TrustEngine/VerifyAttestation"
	TrustEngine_GetFingerprint_FullMethodName    = "/verilink.trust.v1.TrustEngine/GetFingerprint"
)

// TrustEngineClient is the client API for TrustEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrustEngineClient interface {
	RunVeriRank(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunChunk, ScoreTable], error)
	VerifyAttestation(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResult, error)
	GetFingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*Fingerprint, error)
}

type trustEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustEngineClient(cc grpc.ClientConnInterface) TrustEngineClient {
	return &trustEngineClient{cc}
}

func (c *trustEngineClient) RunVeriRank(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunChunk, ScoreTable], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrustEngine_ServiceDesc.Streams[0], TrustEngine_RunVeriRank_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunChunk, ScoreTable]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrustEngine_RunVeriRankClient = grpc.ClientStreamingClient[RunChunk, ScoreTable]

func (c *trustEngineClient) VerifyAttestation(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResult)
	err := c.cc.Invoke(ctx, TrustEngine_VerifyAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustEngineClient) GetFingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*Fingerprint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fingerprint)
	err := c.cc.Invoke(ctx, TrustEngine_GetFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustEngineServer is the server API for TrustEngine service.
// All implementations must embed UnimplementedTrustEngineServer
// for forward compatibility.
type TrustEngineServer interface {
	RunVeriRank(grpc.ClientStreamingServer[RunChunk, ScoreTable]) error
	VerifyAttestation(context.Context, *VerifyRequest) (*VerifyResult, error)
	GetFingerprint(context.Context, *FingerprintRequest) (*Fingerprint, error)
	mustEmbedUnimplementedTrustEngineServer()
}

// UnimplementedTrustEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrustEngineServer struct{}

func (UnimplementedTrustEngineServer) RunVeriRank(grpc.ClientStreamingServer[RunChunk, ScoreTable]) error {
	return status.Errorf(codes.Unimplemented, "method RunVeriRank not implemented")
}
func (UnimplementedTrustEngineServer) VerifyAttestation(context.Context, *VerifyRequest) (*VerifyResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAttestation not implemented")
}
func (UnimplementedTrustEngineServer) GetFingerprint(context.Context, *FingerprintRequest) (*Fingerprint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFingerprint not implemented")
}
func (UnimplementedTrustEngineServer) mustEmbedUnimplementedTrustEngineServer() {}
func (UnimplementedTrustEngineServer) testEmbeddedByValue()                     {}

// UnsafeTrustEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustEngineServer will
// result in compilation errors.
type UnsafeTrustEngineServer interface {
	mustEmbedUnimplementedTrustEngineServer()
}

func RegisterTrustEngineServer(s grpc.ServiceRegistrar, srv TrustEngineServer) {
	// If the following call pancis, it indicates UnimplementedTrustEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrustEngine_ServiceDesc, srv)
}

func _TrustEngine_RunVeriRank_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrustEngineServer).RunVeriRank(&grpc.GenericServerStream[RunChunk, ScoreTable]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrustEngine_RunVeriRankServer = grpc.ClientStreamingServer[RunChunk, ScoreTable]

func _TrustEngine_VerifyAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustEngineServer).VerifyAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustEngine_VerifyAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustEngineServer).VerifyAttestation(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustEngine_GetFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustEngineServer).GetFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustEngine_GetFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustEngineServer).GetFingerprint(ctx, req.(*FingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrustEngine_ServiceDesc is the grpc.ServiceDesc for TrustEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrustEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verilink.trust.v1.TrustEngine",
	HandlerType: (*TrustEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAttestation",
			Handler:    _TrustEngine_VerifyAttestation_Handler,
		},
		{
			MethodName: "GetFingerprint",
			Handler:    _TrustEngine_GetFingerprint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunVeriRank",
			Handler:       _TrustEngine_RunVeriRank_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "trust.proto",
}
