// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: verilink/trust/v1/trust.proto

package trustpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunVeriRank: client-streamed input to stay within gRPC message limits.
// The first chunk MUST be a RunHeader; subsequent chunks are attestations,
// principals, and roots in any order.
type RunChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunChunk_Header
	//	*RunChunk_Attestation
	//	*RunChunk_Principal
	//	*RunChunk_Root
	Payload       isRunChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunChunk) Reset() {
	*x = RunChunk{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunChunk) ProtoMessage() {}

func (x *RunChunk) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunChunk.ProtoReflect.Descriptor instead.
func (*RunChunk) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{0}
}

func (x *RunChunk) GetPayload() isRunChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunChunk) GetHeader() *RunHeader {
	if x != nil {
		if x, ok := x.Payload.(*RunChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RunChunk) GetAttestation() *Attestation {
	if x != nil {
		if x, ok := x.Payload.(*RunChunk_Attestation); ok {
			return x.Attestation
		}
	}
	return nil
}

func (x *RunChunk) GetPrincipal() *Principal {
	if x != nil {
		if x, ok := x.Payload.(*RunChunk_Principal); ok {
			return x.Principal
		}
	}
	return nil
}

func (x *RunChunk) GetRoot() *Root {
	if x != nil {
		if x, ok := x.Payload.(*RunChunk_Root); ok {
			return x.Root
		}
	}
	return nil
}

type isRunChunk_Payload interface {
	isRunChunk_Payload()
}

type RunChunk_Header struct {
	Header *RunHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RunChunk_Attestation struct {
	Attestation *Attestation `protobuf:"bytes,2,opt,name=attestation,proto3,oneof"`
}

type RunChunk_Principal struct {
	Principal *Principal `protobuf:"bytes,3,opt,name=principal,proto3,oneof"`
}

type RunChunk_Root struct {
	Root *Root `protobuf:"bytes,4,opt,name=root,proto3,oneof"`
}

func (*RunChunk_Header) isRunChunk_Payload() {}

func (*RunChunk_Attestation) isRunChunk_Payload() {}

func (*RunChunk_Principal) isRunChunk_Payload() {}

func (*RunChunk_Root) isRunChunk_Payload() {}

type RunHeader struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EvaluationTimeUnix int64                  `protobuf:"varint,1,opt,name=evaluation_time_unix,json=evaluationTimeUnix,proto3" json:"evaluation_time_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunHeader) Reset() {
	*x = RunHeader{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHeader) ProtoMessage() {}

func (x *RunHeader) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHeader.ProtoReflect.Descriptor instead.
func (*RunHeader) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{1}
}

func (x *RunHeader) GetEvaluationTimeUnix() int64 {
	if x != nil {
		return x.EvaluationTimeUnix
	}
	return 0
}

type Attestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IssuerId        string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`    // vrl:p:<uuid>
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // vrl:p:<uuid>
	TrustDelta      int32                  `protobuf:"varint,3,opt,name=trust_delta,json=trustDelta,proto3" json:"trust_delta,omitempty"`
	IssuedAtUnix    int64                  `protobuf:"varint,4,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,5,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	AttestationType string                 `protobuf:"bytes,6,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	ObservationId   string                 `protobuf:"bytes,7,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"` // for split-visibility grouping; empty = no pairing
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{2}
}

func (x *Attestation) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Attestation) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Attestation) GetTrustDelta() int32 {
	if x != nil {
		return x.TrustDelta
	}
	return 0
}

func (x *Attestation) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *Attestation) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Attestation) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *Attestation) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

// Principal: streamed so the engine can stamp entity_kind on output rows.
// Every root, attestation issuer, and attestation subject MUST have a streamed
// Principal row — the server fail-closes (InvalidArgument) otherwise. The
// trust_weight=1.0 default exists only in the legacy in-process path
// (CalculateScores/ReplaceEdgesAndCalculate), not in the gRPC path.
type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                        // vrl:p:<uuid>
	EntityKind    string                 `protobuf:"bytes,2,opt,name=entity_kind,json=entityKind,proto3" json:"entity_kind,omitempty"`      // agent | issuer | both
	TrustWeight   float64                `protobuf:"fixed64,3,opt,name=trust_weight,json=trustWeight,proto3" json:"trust_weight,omitempty"` // 0.0..1.0; required for issuers in the gRPC path
	IsBootstrap   bool                   `protobuf:"varint,4,opt,name=is_bootstrap,json=isBootstrap,proto3" json:"is_bootstrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{3}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetEntityKind() string {
	if x != nil {
		return x.EntityKind
	}
	return ""
}

func (x *Principal) GetTrustWeight() float64 {
	if x != nil {
		return x.TrustWeight
	}
	return 0
}

func (x *Principal) GetIsBootstrap() bool {
	if x != nil {
		return x.IsBootstrap
	}
	return false
}

type Root struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // vrl:p:<uuid> — a bootstrap principal (always an issuer)
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"` // 0.0..1.0; root initializes at 100 * weight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Root) Reset() {
	*x = Root{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Root) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Root) ProtoMessage() {}

func (x *Root) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Root.ProtoReflect.Descriptor instead.
func (*Root) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{4}
}

func (x *Root) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Root) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ScoreTable struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Rows           []*ScoreRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	ComputedAtUnix int64                  `protobuf:"varint,2,opt,name=computed_at_unix,json=computedAtUnix,proto3" json:"computed_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScoreTable) Reset() {
	*x = ScoreTable{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreTable) ProtoMessage() {}

func (x *ScoreTable) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreTable.ProtoReflect.Descriptor instead.
func (*ScoreTable) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreTable) GetRows() []*ScoreRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ScoreTable) GetComputedAtUnix() int64 {
	if x != nil {
		return x.ComputedAtUnix
	}
	return 0
}

type ScoreRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	EntityKind    string                 `protobuf:"bytes,2,opt,name=entity_kind,json=entityKind,proto3" json:"entity_kind,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Blacklisted   bool                   `protobuf:"varint,4,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`
	ScoreReason   string                 `protobuf:"bytes,5,opt,name=score_reason,json=scoreReason,proto3" json:"score_reason,omitempty"` // propagated | blacklisted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRow) Reset() {
	*x = ScoreRow{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRow) ProtoMessage() {}

func (x *ScoreRow) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRow.ProtoReflect.Descriptor instead.
func (*ScoreRow) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreRow) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *ScoreRow) GetEntityKind() string {
	if x != nil {
		return x.EntityKind
	}
	return ""
}

func (x *ScoreRow) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreRow) GetBlacklisted() bool {
	if x != nil {
		return x.Blacklisted
	}
	return false
}

func (x *ScoreRow) GetScoreReason() string {
	if x != nil {
		return x.ScoreReason
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwsToken      string                 `protobuf:"bytes,1,opt,name=jws_token,json=jwsToken,proto3" json:"jws_token,omitempty"`
	CandidateKeys []*KeyCandidate        `protobuf:"bytes,2,rep,name=candidate_keys,json=candidateKeys,proto3" json:"candidate_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyRequest) GetJwsToken() string {
	if x != nil {
		return x.JwsToken
	}
	return ""
}

func (x *VerifyRequest) GetCandidateKeys() []*KeyCandidate {
	if x != nil {
		return x.CandidateKeys
	}
	return nil
}

type KeyCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`             // e.g. k1
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // raw 32-byte Ed25519 public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCandidate) Reset() {
	*x = KeyCandidate{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCandidate) ProtoMessage() {}

func (x *KeyCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCandidate.ProtoReflect.Descriptor instead.
func (*KeyCandidate) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{8}
}

func (x *KeyCandidate) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyCandidate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type VerifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	VerifiedKeyId string                 `protobuf:"bytes,2,opt,name=verified_key_id,json=verifiedKeyId,proto3" json:"verified_key_id,omitempty"` // which candidate matched
	IssuerId      string                 `protobuf:"bytes,3,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Payload       *AttestationPayload    `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResult) Reset() {
	*x = VerifyResult{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResult) ProtoMessage() {}

func (x *VerifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResult.ProtoReflect.Descriptor instead.
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResult) GetVerifiedKeyId() string {
	if x != nil {
		return x.VerifiedKeyId
	}
	return ""
}

func (x *VerifyResult) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *VerifyResult) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *VerifyResult) GetPayload() *AttestationPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AttestationPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttestationType string                 `protobuf:"bytes,1,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	FactsJson       []byte                 `protobuf:"bytes,2,opt,name=facts_json,json=factsJson,proto3" json:"facts_json,omitempty"` // raw verified JSON bytes
	TrustLevelDelta int32                  `protobuf:"varint,3,opt,name=trust_level_delta,json=trustLevelDelta,proto3" json:"trust_level_delta,omitempty"`
	IssuedAtUnix    int64                  `protobuf:"varint,4,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,5,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Jti             string                 `protobuf:"bytes,6,opt,name=jti,proto3" json:"jti,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Visibility      string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"` // participants | public
	ObservationId   string                 `protobuf:"bytes,9,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationPayload) Reset() {
	*x = AttestationPayload{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationPayload) ProtoMessage() {}

func (x *AttestationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationPayload.ProtoReflect.Descriptor instead.
func (*AttestationPayload) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{10}
}

func (x *AttestationPayload) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *AttestationPayload) GetFactsJson() []byte {
	if x != nil {
		return x.FactsJson
	}
	return nil
}

func (x *AttestationPayload) GetTrustLevelDelta() int32 {
	if x != nil {
		return x.TrustLevelDelta
	}
	return 0
}

func (x *AttestationPayload) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *AttestationPayload) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *AttestationPayload) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *AttestationPayload) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AttestationPayload) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *AttestationPayload) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

type FingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ja4           string                 `protobuf:"bytes,1,opt,name=ja4,proto3" json:"ja4,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	KeyHash       string                 `protobuf:"bytes,3,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"` // SHA-256 over raw 32-byte public key
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintRequest) Reset() {
	*x = FingerprintRequest{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintRequest) ProtoMessage() {}

func (x *FingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintRequest.ProtoReflect.Descriptor instead.
func (*FingerprintRequest) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{11}
}

func (x *FingerprintRequest) GetJa4() string {
	if x != nil {
		return x.Ja4
	}
	return ""
}

func (x *FingerprintRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FingerprintRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *FingerprintRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Fingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fingerprint) Reset() {
	*x = Fingerprint{}
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fingerprint) ProtoMessage() {}

func (x *Fingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_verilink_trust_v1_trust_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fingerprint.ProtoReflect.Descriptor instead.
func (*Fingerprint) Descriptor() ([]byte, []int) {
	return file_verilink_trust_v1_trust_proto_rawDescGZIP(), []int{12}
}

func (x *Fingerprint) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_verilink_trust_v1_trust_proto protoreflect.FileDescriptor

const file_verilink_trust_v1_trust_proto_rawDesc = "" +
	"\n" +
	"\x1dverilink/trust/v1/trust.proto\x12\x11verilink.trust.v1\"\xfe\x01\n" +
	"\bRunChunk\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.verilink.trust.v1.RunHeaderH\x00R\x06header\x12B\n" +
	"\vattestation\x18\x02 \x01(\v2\x1e.verilink.trust.v1.AttestationH\x00R\vattestation\x12<\n" +
	"\tprincipal\x18\x03 \x01(\v2\x1c.verilink.trust.v1.PrincipalH\x00R\tprincipal\x12-\n" +
	"\x04root\x18\x04 \x01(\v2\x17.verilink.trust.v1.RootH\x00R\x04rootB\t\n" +
	"\apayload\"=\n" +
	"\tRunHeader\x120\n" +
	"\x14evaluation_time_unix\x18\x01 \x01(\x03R\x12evaluationTimeUnix\"\x8a\x02\n" +
	"\vAttestation\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\vtrust_delta\x18\x03 \x01(\x05R\n" +
	"trustDelta\x12$\n" +
	"\x0eissued_at_unix\x18\x04 \x01(\x03R\fissuedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x05 \x01(\x03R\rexpiresAtUnix\x12)\n" +
	"\x10attestation_type\x18\x06 \x01(\tR\x0fattestationType\x12%\n" +
	"\x0eobservation_id\x18\a \x01(\tR\robservationId\"\x82\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_kind\x18\x02 \x01(\tR\n" +
	"entityKind\x12!\n" +
	"\ftrust_weight\x18\x03 \x01(\x01R\vtrustWeight\x12!\n" +
	"\fis_bootstrap\x18\x04 \x01(\bR\visBootstrap\".\n" +
	"\x04Root\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"g\n" +
	"\n" +
	"ScoreTable\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.verilink.trust.v1.ScoreRowR\x04rows\x12(\n" +
	"\x10computed_at_unix\x18\x02 \x01(\x03R\x0ecomputedAtUnix\"\xa9\x01\n" +
	"\bScoreRow\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x1f\n" +
	"\ventity_kind\x18\x02 \x01(\tR\n" +
	"entityKind\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12 \n" +
	"\vblacklisted\x18\x04 \x01(\bR\vblacklisted\x12!\n" +
	"\fscore_reason\x18\x05 \x01(\tR\vscoreReason\"t\n" +
	"\rVerifyRequest\x12\x1b\n" +
	"\tjws_token\x18\x01 \x01(\tR\bjwsToken\x12F\n" +
	"\x0ecandidate_keys\x18\x02 \x03(\v2\x1f.verilink.trust.v1.KeyCandidateR\rcandidateKeys\"D\n" +
	"\fKeyCandidate\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xdf\x01\n" +
	"\fVerifyResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12&\n" +
	"\x0fverified_key_id\x18\x02 \x01(\tR\rverifiedKeyId\x12\x1b\n" +
	"\tissuer_id\x18\x03 \x01(\tR\bissuerId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12?\n" +
	"\apayload\x18\x05 \x01(\v2%.verilink.trust.v1.AttestationPayloadR\apayload\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xd8\x02\n" +
	"\x12AttestationPayload\x12)\n" +
	"\x10attestation_type\x18\x01 \x01(\tR\x0fattestationType\x12\x1d\n" +
	"\n" +
	"facts_json\x18\x02 \x01(\fR\tfactsJson\x12*\n" +
	"\x11trust_level_delta\x18\x03 \x01(\x05R\x0ftrustLevelDelta\x12$\n" +
	"\x0eissued_at_unix\x18\x04 \x01(\x03R\fissuedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x05 \x01(\x03R\rexpiresAtUnix\x12\x10\n" +
	"\x03jti\x18\x06 \x01(\tR\x03jti\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibility\x12%\n" +
	"\x0eobservation_id\x18\t \x01(\tR\robservationId\"\xe7\x01\n" +
	"\x12FingerprintRequest\x12\x10\n" +
	"\x03ja4\x18\x01 \x01(\tR\x03ja4\x12L\n" +
	"\aheaders\x18\x02 \x03(\v22.verilink.trust.v1.FingerprintRequest.HeadersEntryR\aheaders\x12\x19\n" +
	"\bkey_hash\x18\x03 \x01(\tR\akeyHash\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\vFingerprint\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha2562\x8b\x02\n" +
	"\vTrustEngine\x12K\n" +
	"\vRunVeriRank\x12\x1b.verilink.trust.v1.RunChunk\x1a\x1d.verilink.trust.v1.ScoreTable(\x01\x12V\n" +
	"\x11VerifyAttestation\x12 .verilink.trust.v1.VerifyRequest\x1a\x1f.verilink.trust.v1.VerifyResult\x12W\n" +
	"\x0eGetFingerprint\x12%.verilink.trust.v1.FingerprintRequest\x1a\x1e.verilink.trust.v1.FingerprintB;Z9github.com/messagesgoel-blip/verilink/pkg/trustpb;trustpbb\x06proto3"

var (
	file_verilink_trust_v1_trust_proto_rawDescOnce sync.Once
	file_verilink_trust_v1_trust_proto_rawDescData []byte
)

func file_verilink_trust_v1_trust_proto_rawDescGZIP() []byte {
	file_verilink_trust_v1_trust_proto_rawDescOnce.Do(func() {
		file_verilink_trust_v1_trust_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verilink_trust_v1_trust_proto_rawDesc), len(file_verilink_trust_v1_trust_proto_rawDesc)))
	})
	return file_verilink_trust_v1_trust_proto_rawDescData
}

var file_verilink_trust_v1_trust_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_verilink_trust_v1_trust_proto_goTypes = []any{
	(*RunChunk)(nil),           // 0: verilink.trust.v1.RunChunk
	(*RunHeader)(nil),          // 1: verilink.trust.v1.RunHeader
	(*Attestation)(nil),        // 2: verilink.trust.v1.Attestation
	(*Principal)(nil),          // 3: verilink.trust.v1.Principal
	(*Root)(nil),               // 4: verilink.trust.v1.Root
	(*ScoreTable)(nil),         // 5: verilink.trust.v1.ScoreTable
	(*ScoreRow)(nil),           // 6: verilink.trust.v1.ScoreRow
	(*VerifyRequest)(nil),      // 7: verilink.trust.v1.VerifyRequest
	(*KeyCandidate)(nil),       // 8: verilink.trust.v1.KeyCandidate
	(*VerifyResult)(nil),       // 9: verilink.trust.v1.VerifyResult
	(*AttestationPayload)(nil), // 10: verilink.trust.v1.AttestationPayload
	(*FingerprintRequest)(nil), // 11: verilink.trust.v1.FingerprintRequest
	(*Fingerprint)(nil),        // 12: verilink.trust.v1.Fingerprint
	nil,                        // 13: verilink.trust.v1.FingerprintRequest.HeadersEntry
}
var file_verilink_trust_v1_trust_proto_depIdxs = []int32{
	1,  // 0: verilink.trust.v1.RunChunk.header:type_name -> verilink.trust.v1.RunHeader
	2,  // 1: verilink.trust.v1.RunChunk.attestation:type_name -> verilink.trust.v1.Attestation
	3,  // 2: verilink.trust.v1.RunChunk.principal:type_name -> verilink.trust.v1.Principal
	4,  // 3: verilink.trust.v1.RunChunk.root:type_name -> verilink.trust.v1.Root
	6,  // 4: verilink.trust.v1.ScoreTable.rows:type_name -> verilink.trust.v1.ScoreRow
	8,  // 5: verilink.trust.v1.VerifyRequest.candidate_keys:type_name -> verilink.trust.v1.KeyCandidate
	10, // 6: verilink.trust.v1.VerifyResult.payload:type_name -> verilink.trust.v1.AttestationPayload
	13, // 7: verilink.trust.v1.FingerprintRequest.headers:type_name -> verilink.trust.v1.FingerprintRequest.HeadersEntry
	0,  // 8: verilink.trust.v1.TrustEngine.RunVeriRank:input_type -> verilink.trust.v1.RunChunk
	7,  // 9: verilink.trust.v1.TrustEngine.VerifyAttestation:input_type -> verilink.trust.v1.VerifyRequest
	11, // 10: verilink.trust.v1.TrustEngine.GetFingerprint:input_type -> verilink.trust.v1.FingerprintRequest
	5,  // 11: verilink.trust.v1.TrustEngine.RunVeriRank:output_type -> verilink.trust.v1.ScoreTable
	9,  // 12: verilink.trust.v1.TrustEngine.VerifyAttestation:output_type -> verilink.trust.v1.VerifyResult
	12, // 13: verilink.trust.v1.TrustEngine.GetFingerprint:output_type -> verilink.trust.v1.Fingerprint
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_verilink_trust_v1_trust_proto_init() }
func file_verilink_trust_v1_trust_proto_init() {
	if File_verilink_trust_v1_trust_proto != nil {
		return
	}
	file_verilink_trust_v1_trust_proto_msgTypes[0].OneofWrappers = []any{
		(*RunChunk_Header)(nil),
		(*RunChunk_Attestation)(nil),
		(*RunChunk_Principal)(nil),
		(*RunChunk_Root)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verilink_trust_v1_trust_proto_rawDesc), len(file_verilink_trust_v1_trust_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verilink_trust_v1_trust_proto_goTypes,
		DependencyIndexes: file_verilink_trust_v1_trust_proto_depIdxs,
		MessageInfos:      file_verilink_trust_v1_trust_proto_msgTypes,
	}.Build()
	File_verilink_trust_v1_trust_proto = out.File
	file_verilink_trust_v1_trust_proto_goTypes = nil
	file_verilink_trust_v1_trust_proto_depIdxs = nil
}
